/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FdAmbulanceWlList {
    }
}
declare global {
    interface HTMLFdAmbulanceWlListElement extends Components.FdAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLFdAmbulanceWlListElement: {
        prototype: HTMLFdAmbulanceWlListElement;
        new (): HTMLFdAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "fd-ambulance-wl-list": HTMLFdAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface FdAmbulanceWlList {
    }
    interface IntrinsicElements {
        "fd-ambulance-wl-list": FdAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "fd-ambulance-wl-list": LocalJSX.IntrinsicElements["fd-ambulance-wl-list"] & JSXBase.HTMLAttributes<HTMLFdAmbulanceWlListElement>;
        }
    }
}
